### ISSUE TITLE
[BUG]: Update Speakers

### ISSUE THREAD

**Issue by ashwinexe** [Hackerabad/beyond-the-binary#18]
### Checklist before submitting the issue

- [X] I've searched for existing [Github issues](https://github.com/Hackerabad/beyond-the-binary/issues)

### Description

Reveal all speakers in Speakers section

**Comment by sri-nivas1227** [comment]
@ashwinexe I updated the code. Review once and merge.

**Comment by ashwinexe** [comment]
closed by #19
