### ISSUE TITLE
[BUG]: Update RSVP to Watch Now

### ISSUE THREAD

**Issue by ashwinexe** [Hackerabad/beyond-the-binary#21]
### Checklist before submitting the issue

- [X] I've searched for existing [Github issues](https://github.com/Hackerabad/beyond-the-binary/issues)

### Description

Update RSVP text to **Watch Now** and redirect it to the youtube playlist.

**Comment by sri-nivas1227** [comment]
Link to _Beyond The Binary_ YouTube playlist: `https://youtube.com/playlist?list=PLimLxMcF2Zrin3lX_kgwcArjJA83n4f53`
