### ISSUE TITLE
Add Hack This Fall Logo

### ISSUE THREAD

**Issue by ashwinexe** [Hackerabad/beyond-the-binary#4]
[ ] Add Hack this Fall logo, our latest community partner
[ ] Link their social to the image

HTF Assets here: https://github.com/hack-this-fall/Media-Kit

**Comment by umadhatri** [comment]
Can I try?

**Comment by ashwinexe** [comment]
@umadhatri assigned
Good luck!

**Comment by sri-nivas1227** [comment]
Feel free to ask, if you have any doubt.

**Comment by umadhatri** [comment]
I'll probably badger you a lot 😅
But, I'll try!

**Comment by sri-nivas1227** [comment]
yeah..... don't forget to create a branch for the changes u make... so u won't mess up with your original code🙂

**Comment by umadhatri** [comment]
Ooh, ok! And also one more question, where should I link the image to?

**Comment by umadhatri** [comment]
I can't figure out which URL I should use 😅

**Comment by sri-nivas1227** [comment]
> Ooh, ok! And also one more question, where should I link the image to?

at the bottom, there's a section called community partners.
there u just copy the other comm partner code and change the URL and other required details

**Comment by umadhatri** [comment]
> > Ooh, ok! And also one more question, where should I link the image to?
> 
> at the bottom, there's a section called community partners. there u just copy the other comm partner code and change the URL and other required details

Ok, got it!
I'll do that 😊

**Comment by umadhatri** [comment]
Umm.... guys, I have an error in my command terminal. It says "Support for password authentication was removed August 13, 2021. Please use a personal access token instead" How do I fix this? 🙃 Can you help me out?

**Comment by sri-nivas1227** [comment]
what? can't u login with username and pwd in the terminal?

**Comment by sri-nivas1227** [comment]
`git config --global user.name "your_username"`
`git config --global user.email "your_email_address@example.com"`
Are these the commands U are using?

**Comment by umadhatri** [comment]
> `git config --global user.name "your_username"` `git config --global user.email "your_email_address@example.com"` Are these the commands U are using?

No... They were different, I'll try using these ones again

**Comment by sri-nivas1227** [comment]
OK
Once send those commands you used **before**.

**Comment by umadhatri** [comment]
git remote-v
git remote set-url origin git@github

**Comment by sri-nivas1227** [comment]
have u configured your git local setup with your username.

with these commands
> `git config --global user.name "your_username"`
> `git config --global user.email "your_email_address@example.com"`

**Comment by ashwinexe** [comment]
@umadhatri were you able to push changes to your repo?
If not, let's hop on hackerabad vc and debug it. 
You can ping me in discord server.

**Comment by umadhatri** [comment]
> @umadhatri were you able to push changes to your repo? If not, let's hop on hackerabad vc and debug it. You can ping me in discord server.

Can we do it tonight when I have my laptop?

**Comment by umadhatri** [comment]
Umm... Hey guys, I guess I finally pushed the changes!
Can you take a look at it and let me know if I can do anything else! ☺️

**Comment by ashwinexe** [comment]
#8 has closed this

**Comment by sri-nivas1227** [comment]
Great Job👏🏻....  it looks good 👍🏻
But it is a good practice to push code to a **new branch** than directly pushing to the **main.** 
Coz sometimes the new code may mess up the page if there are some issues. For now, it is ok, but don't forget next time🙂

**Comment by umadhatri** [comment]
> Great Job👏🏻.... it looks good 👍🏻 But it is a good practice to push code to a **new branch** than directly pushing to the **main.** Coz sometimes the new code may mess up the page if there are some issues. For now, it is ok, but don't forget next time🙂

I'll keep that in mind for next time 🙂 And thank you so much for helping me so patiently with the git commands!! I really really appreciate it 😊
